#!/bin/sh
set -e

. ./headers

while getopts ":d" option; do
   case $option in
      d) # Debug
         export CFLAGS="$CFLAGS -DDEBUG"
   esac
done

[ ! -d "kernel_obj" ] && mkdir kernel_obj
rsync -a --include '*/' --exclude '*' kernel/ kernel_obj/

[ ! -d "libc_obj" ] && mkdir libc_obj
rsync -a --include '*/' --exclude '*' libc/ libc_obj/

for PROJECT in $PROJECTS; do
  (cd $PROJECT && DESTDIR="$SYSROOT" $MAKE install $MFLAGS)
done