#include <kernel/tools.h>

FGET_REGISTER(eax)
FGET_REGISTER(ebx)
FGET_REGISTER(ecx)
FGET_REGISTER(edx)

FGET_REGISTER(esp)
FGET_REGISTER(ebp)

FGET_REGISTER(esi)
FGET_REGISTER(edi)

FGET_CTRL_REGISTER(0)
FGET_CTRL_REGISTER(2)
FGET_CTRL_REGISTER(3)
FGET_CTRL_REGISTER(4)